### ISSUE TITLE
Fallimento Prova 1

### ISSUE THREAD

**Issue by EduBic** [LeafSWE/clips#26]
## Scopo prova

Visualizzare dall’applicazione le indicazioni attese per raggiungere la destinazione
$END.
### Input

```
$START = 1AD100 (ROI = 01000)
$CAT = Aule
$END = 1BC45
```

```
$START = 1C150 (ROI = 01002)
$CAT = Toilette
$END = Toilette donne 1AD
```
### Output

Nexus 5.01 e Moto G 6.00 generano un crash subito dopo la visualizzazione delle istruzioni per la navigazione mentre il Galaxy S5 Mini non rileva problemi.

Eccezioni sollevate:
`//LOLLIPOP
    05-31 16:45:41.057 22511-22511/com.leaf.clips E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.leaf.clips, PID: 22511
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundColor(int)' on a null object reference
                                                                    at com.leaf.clips.view.NavigationViewImp.refreshInstructions(NavigationViewImp.java:103)
                                                                    at com.leaf.clips.presenter.NavigationActivity.informationUpdate(NavigationActivity.java:258)
                                                                    at com.leaf.clips.model.NavigationManagerImp.onReceive(NavigationManagerImp.java:243)
                                                                    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                    at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                    at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

```
//MARSHMALLOW
    05-31 16:55:25.128 9523-9523/com.leaf.clips E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.leaf.clips, PID: 9523
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundColor(int)' on a null object reference
                                                                  at com.leaf.clips.view.NavigationViewImp.refreshInstructions(NavigationViewImp.java:103)
                                                                  at com.leaf.clips.presenter.NavigationActivity.informationUpdate(NavigationActivity.java:258)
                                                                  at com.leaf.clips.model.NavigationManagerImp.onReceive(NavigationManagerImp.java:243)
                                                                  at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                  at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                  at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by o5k1** [comment]
SI può chiudere?

**Comment by EduBic** [comment]
Ho ricontrollato i test e funziona tutto.
